/**
 * This is an autogenerated file. Do not edit this file manually.
 *
 * key_pair.ts gives private and public key for signing the requests 
 * in all test in the `Settle fees` section in serving.spec.ts.
 */

import { BigNumberish } from "ethers";

export const privateKey: [BigNumberish, BigNumberish] = [
    BigInt(`0xd5bb0856cd1da395cbccb9d56c1c7822`),
    BigInt(`0x7e5257fa72fc10f9440ebf19fbf8f93`),
];

export const publicKey: [BigNumberish, BigNumberish] = [
    BigInt(`0x3c9900a4e51658b51f3448e1050b2214`),
    BigInt(`0x29af48b33e83c1844cf1bc62c6cdf9ec`),
];
