/**
 * This is an autogenerated file. Do not edit this file manually.
 *
 * key_pair.ts gives private and public key for signing the requests 
 * in all test in the `Settle fees` section in serving.spec.ts.
 */

import { BigNumberish } from "ethers";

export const privateKey: [BigNumberish, BigNumberish] = [
    BigInt(`0xdd2a408b1603b4e5c7967b94c4445b47`),
    BigInt(`0x28da9331b3d97d630fb3f081f3fb1309`),
];

export const publicKey: [BigNumberish, BigNumberish] = [
    BigInt(`0x181f06aa76b99ed1bc48ccfbf1b295a4`),
    BigInt(`0x80e341f2b8a1c8178bd90b222ffb43b3`),
];
