/**
 * This is an autogenerated file. Do not edit this file manually.
 *
 * key_pair.ts gives private and public key for signing the requests 
 * in all test in the `Settle fees` section in serving.spec.ts.
 */

import { BigNumberish } from "ethers";

export const privateKey: [BigNumberish, BigNumberish] = [
    BigInt(`0xb7717882b878ede49ffb00189b6970dc`),
    BigInt(`0x174b5521da3d6b8f6616bd96ef0bcb4`),
];

export const publicKey: [BigNumberish, BigNumberish] = [
    BigInt(`0xa4d16d5a539ca03b123cf600b0ed4930`),
    BigInt(`0xa5485694c082cb160bdacb7023a74af0`),
];
