/**
 * This is an autogenerated file. Do not edit this file manually.
 *
 * key_pair.ts gives private and public key for signing the requests 
 * in all test in the `Settle fees` section in serving.spec.ts.
 */

import { BigNumberish } from "ethers";

export const privateKey: [BigNumberish, BigNumberish] = [
    BigInt(`0xf762647a882708c3beb586a9c0528b85`),
    BigInt(`0xaf6b9be57a639441f8dcadb4669afcb`),
];

export const publicKey: [BigNumberish, BigNumberish] = [
    BigInt(`0x84f0df9d9c0a1ed42e1a425add018f07`),
    BigInt(`0xaf6128fcd77cd26ff31eda85fa4f2f91`),
];
