/**
 * This is an autogenerated file. Do not edit this file manually.
 *
 * key_pair.ts gives private and public key for signing the requests 
 * in all test in the `Settle fees` section in serving.spec.ts.
 */

import { BigNumberish } from "ethers";

export const privateKey: [BigNumberish, BigNumberish] = [
    BigInt(`0x98e45d1c83983e7c0731252f6ae3c007`),
    BigInt(`0xb9b4b8b09e22611591af3c3173341dc`),
];

export const publicKey: [BigNumberish, BigNumberish] = [
    BigInt(`0x843712d2e3adb33fd8382f6f47f49db5`),
    BigInt(`0x74c4cfdc32cfe4d81f936c92b8a8dbe`),
];
