/**
 * This is an autogenerated file. Do not edit this file manually.
 *
 * key_pair.ts gives private and public key for signing the requests 
 * in all test in the `Settle fees` section in serving.spec.ts.
 */

import { BigNumberish } from "ethers";

export const privateKey: [BigNumberish, BigNumberish] = [
    BigInt(`0xe58d9507ad7ce920804c14dee698e52a`),
    BigInt(`0x12155e0946f96d56120cf57eeb48629b`),
];

export const publicKey: [BigNumberish, BigNumberish] = [
    BigInt(`0xd1fee047e30fde91f3e62ca081fcacf0`),
    BigInt(`0x26619baec6f13152a1b06212b10964d6`),
];
