/**
 * This is an autogenerated file. Do not edit this file manually.
 *
 * key_pair.ts gives private and public key for signing the requests 
 * in all test in the `Settle fees` section in serving.spec.ts.
 */

import { BigNumberish } from "ethers";

export const privateKey: [BigNumberish, BigNumberish] = [
    BigInt(`0x9df4027b0f0801a5cfc5fdd3b8a7efd0`),
    BigInt(`0x7d9ededd621b5be3904e15d7554e261`),
];

export const publicKey: [BigNumberish, BigNumberish] = [
    BigInt(`0x43e31457dc3e923ef4d2ce8bbcea0d81`),
    BigInt(`0x20564bf3ac684cde6183350b5d9e8de2`),
];
