/**
 * This is an autogenerated file. Do not edit this file manually.
 *
 * key_pair.ts gives private and public key for signing the requests 
 * in all test in the `Settle fees` section in serving.spec.ts.
 */

import { BigNumberish } from "ethers";

export const privateKey: [BigNumberish, BigNumberish] = [
    BigInt(`0x951afaf3778aa240a5ededf2abbb46c7`),
    BigInt(`0x26bea0ef426f14ebb4a0f2cbf2ba5163`),
];

export const publicKey: [BigNumberish, BigNumberish] = [
    BigInt(`0x7aff2506d9ba2df8f48f552feed68468`),
    BigInt(`0x8107aede44025ea329e2b70f01692018`),
];
