/**
 * This is an autogenerated file. Do not edit this file manually.
 *
 * key_pair.ts gives private and public key for signing the requests 
 * in all test in the `Settle fees` section in serving.spec.ts.
 */

import { BigNumberish } from "ethers";

export const privateKey: [BigNumberish, BigNumberish] = [
    BigInt(`0x77e06741b67d951716461a1d6fcf5175`),
    BigInt(`0x1bc28dbfae6f20ffa0c5e23d78c0058f`),
];

export const publicKey: [BigNumberish, BigNumberish] = [
    BigInt(`0xff3fcd5215b63279cee63f1a603dba32`),
    BigInt(`0xa4e13d2f4f51e5f57945c5b950494f9f`),
];
