/**
 * This is an autogenerated file. Do not edit this file manually.
 *
 * key_pair.ts gives private and public key for signing the requests 
 * in all test in the `Settle fees` section in serving.spec.ts.
 */

import { BigNumberish } from "ethers";

export const privateKey: [BigNumberish, BigNumberish] = [
    BigInt(`0x64fc715737646713f5c742cd6aaa777f`),
    BigInt(`0x5079ce6260ccd8252be918fbf2ccb16`),
];

export const publicKey: [BigNumberish, BigNumberish] = [
    BigInt(`0xaa0e73a5aff63d5787b559a3d04e6e90`),
    BigInt(`0xac7b86c85b060277a4bf37ba46fa1cf3`),
];
